codecov:
  notify:
    after_n_builds: 2
  require_ci_to_pass: true
  ci:
    - zivgitlab.uni-muenster.de
comment:
  behavior: once
  layout: 'header, flags, files'
  after_n_builds: 2
coverage:
  precision: 2
  range: 70..100
  round: down
  status:
    changes: false
    project:
      pymor:
        # since we have no policy on this might as well turn this off entirely
        target: 0%
        flags:
          - gitlab_ci
          - github_actions
    patch:
      pymor:
        target: 0%
